fix(unique_six): Remove missing function (#842)
## 🚀 Summary
Refs: _link to or id of ticket_

Briefly describe the changes introduced in this PR.
The `get_six_api_client` has been removed from `unique_six` in favor of
the caller to declare this

```python
>>> from unique_six.client import SixApiClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/azeezraheem/Documents/workspace/ai/postprocessors/unique_stock_ticker/.venv/lib/python3.12/site-packages/unique_six/__init__.py", line 1, in <module>
    from unique_six.client import (
ImportError: cannot import name 'get_six_api_client' from 'unique_six.client' (/Users/azeezraheem/Documents/workspace/ai/postprocessors/unique_stock_ticker/.venv/lib/python3.12/site-packages/unique_six/client.py)

```

## ✅ Changes

- [X] fixed bug / updated docs
- [ ] Refactored code / cleaned up
- [ ] Other (describe below)

## 🧪 Testing

Explain what has been tested and how.

---------

Co-authored-by: Azeez Raheem <raheemazeez4@gmil.com>